language: node_js

services:
  - docker

before_script:
  - npm install

script:
  - docker build -t nodeapi .

after_success:
  - docker login - $docker_id -p $docker_password
  - docker tag nodeapi $docker_id/nodeapi:$TRAVIS_BUILD_NUMBER
  - docker tag nodeapi $docker_id/nodeapi:latest
  - docker push $docker_id/nodeapi:latest
